### ISSUE TITLE
Consider an alternative implementation that helps the compiler emitting SIMD instructions

### ISSUE THREAD

**Issue by giovannicuccu** [pythonspeed/mandelbrot-simd#3]
Hi, after reading you post on pyhtonspeed I wondered if there was a way to modify the scalar code and getting the compiler to create a binary that uses SIMD instructions.
I created a fork https://github.com/giovannicuccu/mandelbrot-simd and developed a new mandelbrot implementation that achieves the goal. My solution is not as fast as the simd implementation, but it's faster than the scalar one and relies on stable rust features. I tested only with compiler flags `-Ctarget-cpu=native` but I think it's worth exploring it.
are you interested in a PR?

**Comment by itamarst** [comment]
Mostly this repo is here for educational purposes, and ... that sounds pretty educational. Looks like you did it as a third variant in addition to the existing two? Maybe rename it "autovectorization" which is the jargon for compiler-emitted SIMD.

So yes, happy for PR.

**Comment by itamarst** [comment]
Done, thank you!
