### ISSUE TITLE
Add a variant using the `pulp` crate

### ISSUE THREAD

**Issue by itamarst** [pythonspeed/mandelbrot-simd#5]
It's a bit different architecturally, but seems pretty cool.

**Comment by itamarst** [comment]
@sarah-quinones if you ever have the time, you could probably do this way faster than I could: I'm trying to implement all the different API variants in one repo.

**Comment by sarah-quinones** [comment]
sure thing, i actually made one last week. im a bit busy right now but i can clean it up and send it your way next weekend

**Comment by sarah-quinones** [comment]
#7 opened a PR

**Comment by itamarst** [comment]
Fixed by #7.

Interestingly on my computer `pulp` is somewhat slower than `std::simd` (but faster than `wide`, so second fastest).

**Comment by sarah-quinones** [comment]
if you don't have avx 512, the reason might be that the larger vector width with std simd is making it unroll the loop

**Comment by itamarst** [comment]
I'm on i7-12700 so yeah there's no AVX-512.
